/**
 * Balanced Diet Analyzer - Local Nutrition Dataset
 * Over 250 common kitchen ingredients with standard nutritional values (per 100g serving)
 * Used as automatic fallback when Spoonacular API is unavailable, rate-limited, or offline.
 */

const LOCAL_NUTRITION_DATABASE = {
    // --------------------------------------------------------------------------
    // PROTEINS & SEAFOOD (High Protein, Variable Fat)
    // --------------------------------------------------------------------------
    "chicken": { name: "Chicken", protein: 27.0, carbohydrates: 0.0, fat: 3.6, fiber: 0.0, isVegetable: false },
    "chicken breast": { name: "Chicken Breast", protein: 31.0, carbohydrates: 0.0, fat: 3.6, fiber: 0.0, isVegetable: false },
    "chicken thigh": { name: "Chicken Thigh", protein: 24.0, carbohydrates: 0.0, fat: 8.0, fiber: 0.0, isVegetable: false },
    "chicken wings": { name: "Chicken Wings", protein: 20.0, carbohydrates: 0.0, fat: 14.0, fiber: 0.0, isVegetable: false },
    "turkey": { name: "Turkey", protein: 29.0, carbohydrates: 0.0, fat: 7.0, fiber: 0.0, isVegetable: false },
    "duck": { name: "Duck", protein: 19.0, carbohydrates: 0.0, fat: 15.0, fiber: 0.0, isVegetable: false },
    "beef": { name: "Beef", protein: 26.0, carbohydrates: 0.0, fat: 15.0, fiber: 0.0, isVegetable: false },
    "ground beef": { name: "Ground Beef", protein: 24.0, carbohydrates: 0.0, fat: 15.0, fiber: 0.0, isVegetable: false },
    "steak": { name: "Steak", protein: 28.0, carbohydrates: 0.0, fat: 12.0, fiber: 0.0, isVegetable: false },
    "pork": { name: "Pork", protein: 25.0, carbohydrates: 0.0, fat: 14.0, fiber: 0.0, isVegetable: false },
    "pork chop": { name: "Pork Chop", protein: 26.0, carbohydrates: 0.0, fat: 10.0, fiber: 0.0, isVegetable: false },
    "bacon": { name: "Bacon", protein: 14.0, carbohydrates: 1.5, fat: 42.0, fiber: 0.0, isVegetable: false },
    "ham": { name: "Ham", protein: 21.0, carbohydrates: 1.5, fat: 5.5, fiber: 0.0, isVegetable: false },
    "lamb": { name: "Lamb", protein: 25.0, carbohydrates: 0.0, fat: 16.0, fiber: 0.0, isVegetable: false },
    "mutton": { name: "Mutton", protein: 25.0, carbohydrates: 0.0, fat: 17.0, fiber: 0.0, isVegetable: false },
    
    // Seafood (Protein + Healthy Fats)
    "fish": { name: "Fish", protein: 20.0, carbohydrates: 0.0, fat: 10.0, fiber: 0.0, isVegetable: false },
    "salmon": { name: "Salmon", protein: 20.0, carbohydrates: 0.0, fat: 13.0, fiber: 0.0, isVegetable: false },
    "tuna": { name: "Tuna", protein: 28.0, carbohydrates: 0.0, fat: 6.0, fiber: 0.0, isVegetable: false },
    "canned tuna": { name: "Canned Tuna", protein: 26.0, carbohydrates: 0.0, fat: 3.0, fiber: 0.0, isVegetable: false },
    "cod": { name: "Cod", protein: 18.0, carbohydrates: 0.0, fat: 0.7, fiber: 0.0, isVegetable: false },
    "tilapia": { name: "Tilapia", protein: 26.0, carbohydrates: 0.0, fat: 2.7, fiber: 0.0, isVegetable: false },
    "trout": { name: "Trout", protein: 21.0, carbohydrates: 0.0, fat: 6.6, fiber: 0.0, isVegetable: false },
    "mackerel": { name: "Mackerel", protein: 19.0, carbohydrates: 0.0, fat: 14.0, fiber: 0.0, isVegetable: false },
    "sardines": { name: "Sardines", protein: 25.0, carbohydrates: 0.0, fat: 11.0, fiber: 0.0, isVegetable: false },
    "shrimp": { name: "Shrimp", protein: 24.0, carbohydrates: 0.2, fat: 0.3, fiber: 0.0, isVegetable: false },
    "prawns": { name: "Prawns", protein: 24.0, carbohydrates: 0.2, fat: 0.3, fiber: 0.0, isVegetable: false },
    "crab": { name: "Crab", protein: 19.0, carbohydrates: 0.0, fat: 1.5, fiber: 0.0, isVegetable: false },
    "lobster": { name: "Lobster", protein: 19.0, carbohydrates: 1.3, fat: 0.9, fiber: 0.0, isVegetable: false },
    "scallops": { name: "Scallops", protein: 17.0, carbohydrates: 3.2, fat: 0.8, fiber: 0.0, isVegetable: false },
    "squid": { name: "Squid", protein: 16.0, carbohydrates: 3.1, fat: 1.4, fiber: 0.0, isVegetable: false },
    "calamari": { name: "Calamari", protein: 16.0, carbohydrates: 3.1, fat: 1.4, fiber: 0.0, isVegetable: false },
    "clams": { name: "Clams", protein: 15.0, carbohydrates: 5.0, fat: 1.0, fiber: 0.0, isVegetable: false },
    "oysters": { name: "Oysters", protein: 9.0, carbohydrates: 4.9, fat: 2.5, fiber: 0.0, isVegetable: false },
    "mussels": { name: "Mussels", protein: 12.0, carbohydrates: 3.7, fat: 2.2, fiber: 0.0, isVegetable: false },
    "anchovies": { name: "Anchovies", protein: 29.0, carbohydrates: 0.0, fat: 10.0, fiber: 0.0, isVegetable: false },

    // Eggs & Dairy (Protein + Healthy Fats)
    "egg": { name: "Egg", protein: 12.6, carbohydrates: 1.1, fat: 9.5, fiber: 0.0, isVegetable: false },
    "eggs": { name: "Eggs", protein: 12.6, carbohydrates: 1.1, fat: 9.5, fiber: 0.0, isVegetable: false },
    "boiled egg": { name: "Boiled Egg", protein: 12.6, carbohydrates: 1.1, fat: 9.5, fiber: 0.0, isVegetable: false },
    "fried egg": { name: "Fried Egg", protein: 13.5, carbohydrates: 0.8, fat: 14.8, fiber: 0.0, isVegetable: false },
    "egg white": { name: "Egg White", protein: 10.9, carbohydrates: 0.7, fat: 0.2, fiber: 0.0, isVegetable: false },
    "egg yolk": { name: "Egg Yolk", protein: 15.9, carbohydrates: 3.6, fat: 26.5, fiber: 0.0, isVegetable: false },
    "paneer": { name: "Paneer", protein: 18.0, carbohydrates: 3.5, fat: 20.0, fiber: 0.0, isVegetable: false },
    "tofu": { name: "Tofu", protein: 8.0, carbohydrates: 1.9, fat: 4.8, fiber: 0.3, isVegetable: false },
    "firm tofu": { name: "Firm Tofu", protein: 12.0, carbohydrates: 2.5, fat: 6.0, fiber: 0.8, isVegetable: false },
    "tempeh": { name: "Tempeh", protein: 19.0, carbohydrates: 9.4, fat: 11.0, fiber: 4.0, isVegetable: false },
    "seitan": { name: "Seitan", protein: 25.0, carbohydrates: 4.0, fat: 1.5, fiber: 0.5, isVegetable: false },
    "edamame": { name: "Edamame", protein: 11.9, carbohydrates: 8.9, fat: 5.2, fiber: 5.2, isVegetable: false },
    "milk": { name: "Milk", protein: 3.4, carbohydrates: 4.8, fat: 3.3, fiber: 0.0, isVegetable: false },
    "yogurt": { name: "Yogurt", protein: 4.5, carbohydrates: 6.0, fat: 3.5, fiber: 0.0, isVegetable: false },
    "curd": { name: "Curd", protein: 4.5, carbohydrates: 6.0, fat: 3.5, fiber: 0.0, isVegetable: false },
    "greek yogurt": { name: "Greek Yogurt", protein: 10.0, carbohydrates: 3.6, fat: 5.0, fiber: 0.0, isVegetable: false },
    "cottage cheese": { name: "Cottage Cheese", protein: 11.0, carbohydrates: 3.4, fat: 4.3, fiber: 0.0, isVegetable: false },
    "cheese": { name: "Cheese", protein: 25.0, carbohydrates: 1.3, fat: 33.0, fiber: 0.0, isVegetable: false },
    "cheddar": { name: "Cheddar Cheese", protein: 25.0, carbohydrates: 1.3, fat: 33.0, fiber: 0.0, isVegetable: false },
    "mozzarella": { name: "Mozzarella", protein: 22.0, carbohydrates: 2.2, fat: 22.0, fiber: 0.0, isVegetable: false },
    "parmesan": { name: "Parmesan", protein: 36.0, carbohydrates: 4.1, fat: 26.0, fiber: 0.0, isVegetable: false },
    "feta": { name: "Feta Cheese", protein: 14.0, carbohydrates: 4.1, fat: 21.0, fiber: 0.0, isVegetable: false },
    "whey protein": { name: "Whey Protein", protein: 80.0, carbohydrates: 5.0, fat: 3.0, fiber: 0.0, isVegetable: false },

    // Legumes (Protein + Carbohydrates + Fiber)
    "chickpeas": { name: "Chickpeas", protein: 8.9, carbohydrates: 27.4, fat: 2.6, fiber: 7.6, isVegetable: false },
    "chana": { name: "Chana", protein: 8.9, carbohydrates: 27.4, fat: 2.6, fiber: 7.6, isVegetable: false },
    "garbanzo beans": { name: "Garbanzo Beans", protein: 8.9, carbohydrates: 27.4, fat: 2.6, fiber: 7.6, isVegetable: false },
    "lentils": { name: "Lentils", protein: 9.0, carbohydrates: 20.0, fat: 0.4, fiber: 7.9, isVegetable: false },
    "dal": { name: "Dal", protein: 9.0, carbohydrates: 20.0, fat: 0.4, fiber: 7.9, isVegetable: false },
    "daal": { name: "Daal", protein: 9.0, carbohydrates: 20.0, fat: 0.4, fiber: 7.9, isVegetable: false },
    "red lentils": { name: "Red Lentils", protein: 9.0, carbohydrates: 20.0, fat: 0.4, fiber: 7.9, isVegetable: false },
    "brown lentils": { name: "Brown Lentils", protein: 9.0, carbohydrates: 20.0, fat: 0.4, fiber: 7.9, isVegetable: false },
    "black beans": { name: "Black Beans", protein: 8.9, carbohydrates: 23.7, fat: 0.5, fiber: 8.7, isVegetable: false },
    "kidney beans": { name: "Kidney Beans", protein: 8.7, carbohydrates: 22.8, fat: 0.5, fiber: 7.4, isVegetable: false },
    "rajma": { name: "Rajma", protein: 8.7, carbohydrates: 22.8, fat: 0.5, fiber: 7.4, isVegetable: false },
    "pinto beans": { name: "Pinto Beans", protein: 9.0, carbohydrates: 26.0, fat: 0.7, fiber: 9.0, isVegetable: false },
    "navy beans": { name: "Navy Beans", protein: 9.7, carbohydrates: 26.0, fat: 0.6, fiber: 10.5, isVegetable: false },
    "cannellini beans": { name: "Cannellini Beans", protein: 9.0, carbohydrates: 24.0, fat: 0.5, fiber: 7.0, isVegetable: false },
    "soybeans": { name: "Soybeans", protein: 18.2, carbohydrates: 9.9, fat: 9.0, fiber: 6.0, isVegetable: false },
    "black eyed peas": { name: "Black Eyed Peas", protein: 7.7, carbohydrates: 21.0, fat: 0.5, fiber: 6.5, isVegetable: false },
    "split peas": { name: "Split Peas", protein: 8.3, carbohydrates: 21.1, fat: 0.4, fiber: 8.3, isVegetable: false },

    // --------------------------------------------------------------------------
    // CARBOHYDRATES & GRAINS (High Carbohydrates)
    // --------------------------------------------------------------------------
    "rice": { name: "Rice", protein: 2.7, carbohydrates: 28.2, fat: 0.3, fiber: 0.4, isVegetable: false },
    "white rice": { name: "White Rice", protein: 2.7, carbohydrates: 28.2, fat: 0.3, fiber: 0.4, isVegetable: false },
    "brown rice": { name: "Brown Rice", protein: 2.6, carbohydrates: 23.0, fat: 0.9, fiber: 1.8, isVegetable: false },
    "basmati rice": { name: "Basmati Rice", protein: 3.0, carbohydrates: 25.0, fat: 0.4, fiber: 0.5, isVegetable: false },
    "jasmine rice": { name: "Jasmine Rice", protein: 2.5, carbohydrates: 27.0, fat: 0.2, fiber: 0.4, isVegetable: false },
    "wild rice": { name: "Wild Rice", protein: 4.0, carbohydrates: 21.3, fat: 0.3, fiber: 1.8, isVegetable: false },
    "oats": { name: "Oats", protein: 16.9, carbohydrates: 66.3, fat: 6.9, fiber: 10.6, isVegetable: false },
    "oatmeal": { name: "Oatmeal", protein: 13.0, carbohydrates: 67.0, fat: 6.5, fiber: 10.0, isVegetable: false },
    "rolled oats": { name: "Rolled Oats", protein: 13.5, carbohydrates: 68.0, fat: 6.5, fiber: 10.0, isVegetable: false },
    "quinoa": { name: "Quinoa", protein: 4.4, carbohydrates: 21.3, fat: 1.9, fiber: 2.8, isVegetable: false },
    "potato": { name: "Potato", protein: 2.0, carbohydrates: 17.5, fat: 0.1, fiber: 2.2, isVegetable: false },
    "potatoes": { name: "Potatoes", protein: 2.0, carbohydrates: 17.5, fat: 0.1, fiber: 2.2, isVegetable: false },
    "baked potato": { name: "Baked Potato", protein: 2.5, carbohydrates: 21.0, fat: 0.2, fiber: 2.3, isVegetable: false },
    "sweet potato": { name: "Sweet Potato", protein: 1.6, carbohydrates: 20.1, fat: 0.1, fiber: 3.0, isVegetable: false },
    "sweet potatoes": { name: "Sweet Potatoes", protein: 1.6, carbohydrates: 20.1, fat: 0.1, fiber: 3.0, isVegetable: false },
    "yam": { name: "Yam", protein: 1.5, carbohydrates: 27.9, fat: 0.2, fiber: 4.1, isVegetable: false },
    "bread": { name: "Bread", protein: 9.0, carbohydrates: 49.0, fat: 3.2, fiber: 2.7, isVegetable: false },
    "white bread": { name: "White Bread", protein: 7.5, carbohydrates: 50.0, fat: 2.5, fiber: 2.0, isVegetable: false },
    "wheat bread": { name: "Wheat Bread", protein: 10.0, carbohydrates: 45.0, fat: 3.5, fiber: 6.0, isVegetable: false },
    "whole wheat bread": { name: "Whole Wheat Bread", protein: 10.0, carbohydrates: 45.0, fat: 3.5, fiber: 6.0, isVegetable: false },
    "sourdough": { name: "Sourdough", protein: 8.0, carbohydrates: 48.0, fat: 1.0, fiber: 2.2, isVegetable: false },
    "bagel": { name: "Bagel", protein: 10.0, carbohydrates: 53.0, fat: 1.5, fiber: 2.3, isVegetable: false },
    "pita": { name: "Pita Bread", protein: 9.0, carbohydrates: 55.0, fat: 1.2, fiber: 2.2, isVegetable: false },
    "roti": { name: "Roti", protein: 8.0, carbohydrates: 47.0, fat: 3.7, fiber: 3.9, isVegetable: false },
    "chapati": { name: "Chapati", protein: 8.0, carbohydrates: 47.0, fat: 3.7, fiber: 3.9, isVegetable: false },
    "naan": { name: "Naan", protein: 8.7, carbohydrates: 51.0, fat: 5.5, fiber: 2.2, isVegetable: false },
    "tortilla": { name: "Tortilla", protein: 6.0, carbohydrates: 45.0, fat: 6.5, fiber: 3.0, isVegetable: false },
    "corn tortilla": { name: "Corn Tortilla", protein: 5.5, carbohydrates: 44.0, fat: 2.5, fiber: 5.5, isVegetable: false },
    "pasta": { name: "Pasta", protein: 5.8, carbohydrates: 30.9, fat: 0.9, fiber: 1.8, isVegetable: false },
    "spaghetti": { name: "Spaghetti", protein: 5.8, carbohydrates: 30.9, fat: 0.9, fiber: 1.8, isVegetable: false },
    "macaroni": { name: "Macaroni", protein: 5.5, carbohydrates: 31.0, fat: 0.9, fiber: 1.8, isVegetable: false },
    "penne": { name: "Penne", protein: 5.8, carbohydrates: 30.9, fat: 0.9, fiber: 1.8, isVegetable: false },
    "noodles": { name: "Noodles", protein: 4.5, carbohydrates: 25.0, fat: 2.0, fiber: 1.2, isVegetable: false },
    "ramen": { name: "Ramen", protein: 4.5, carbohydrates: 26.0, fat: 4.0, fiber: 1.2, isVegetable: false },
    "soba": { name: "Soba Noodles", protein: 5.1, carbohydrates: 21.4, fat: 0.1, fiber: 1.4, isVegetable: false },
    "udon": { name: "Udon", protein: 3.0, carbohydrates: 21.0, fat: 0.4, fiber: 0.8, isVegetable: false },
    "couscous": { name: "Couscous", protein: 3.8, carbohydrates: 23.2, fat: 0.2, fiber: 1.4, isVegetable: false },
    "barley": { name: "Barley", protein: 2.3, carbohydrates: 28.2, fat: 0.4, fiber: 3.8, isVegetable: false },
    "bulgur": { name: "Bulgur", protein: 3.1, carbohydrates: 18.6, fat: 0.2, fiber: 4.5, isVegetable: false },
    "millet": { name: "Millet", protein: 3.5, carbohydrates: 23.7, fat: 1.0, fiber: 1.3, isVegetable: false },
    "buckwheat": { name: "Buckwheat", protein: 3.4, carbohydrates: 20.0, fat: 0.6, fiber: 2.7, isVegetable: false },
    "corn": { name: "Corn", protein: 3.3, carbohydrates: 19.0, fat: 1.4, fiber: 2.4, isVegetable: false },
    "sweet corn": { name: "Sweet Corn", protein: 3.3, carbohydrates: 19.0, fat: 1.4, fiber: 2.4, isVegetable: false },
    "polenta": { name: "Polenta", protein: 2.0, carbohydrates: 17.0, fat: 0.3, fiber: 1.5, isVegetable: false },
    "flour": { name: "Flour", protein: 10.0, carbohydrates: 76.0, fat: 1.0, fiber: 2.7, isVegetable: false },
    "cornmeal": { name: "Cornmeal", protein: 8.1, carbohydrates: 77.0, fat: 3.6, fiber: 7.3, isVegetable: false },
    "tapioca": { name: "Tapioca", protein: 0.2, carbohydrates: 88.0, fat: 0.0, fiber: 0.9, isVegetable: false },
    "cassava": { name: "Cassava", protein: 1.4, carbohydrates: 38.0, fat: 0.3, fiber: 1.8, isVegetable: false },
    "plantain": { name: "Plantain", protein: 1.3, carbohydrates: 32.0, fat: 0.4, fiber: 2.3, isVegetable: false },

    // --------------------------------------------------------------------------
    // VEGETABLES & FIBER (High Fiber, Micronutrients)
    // --------------------------------------------------------------------------
    "spinach": { name: "Spinach", protein: 2.9, carbohydrates: 3.6, fat: 0.4, fiber: 2.2, isVegetable: true },
    "kale": { name: "Kale", protein: 2.9, carbohydrates: 4.4, fat: 1.5, fiber: 4.1, isVegetable: true },
    "lettuce": { name: "Lettuce", protein: 1.4, carbohydrates: 2.9, fat: 0.2, fiber: 1.3, isVegetable: true },
    "romaine": { name: "Romaine Lettuce", protein: 1.2, carbohydrates: 3.3, fat: 0.3, fiber: 2.1, isVegetable: true },
    "arugula": { name: "Arugula", protein: 2.6, carbohydrates: 3.7, fat: 0.7, fiber: 1.6, isVegetable: true },
    "cabbage": { name: "Cabbage", protein: 1.3, carbohydrates: 5.8, fat: 0.1, fiber: 2.5, isVegetable: true },
    "red cabbage": { name: "Red Cabbage", protein: 1.4, carbohydrates: 7.4, fat: 0.2, fiber: 2.1, isVegetable: true },
    "bok choy": { name: "Bok Choy", protein: 1.5, carbohydrates: 2.2, fat: 0.2, fiber: 1.0, isVegetable: true },
    "swiss chard": { name: "Swiss Chard", protein: 1.8, carbohydrates: 3.7, fat: 0.2, fiber: 1.6, isVegetable: true },
    "collard greens": { name: "Collard Greens", protein: 3.0, carbohydrates: 5.4, fat: 0.6, fiber: 4.0, isVegetable: true },
    "broccoli": { name: "Broccoli", protein: 2.8, carbohydrates: 6.6, fat: 0.4, fiber: 2.6, isVegetable: true },
    "broccolini": { name: "Broccolini", protein: 2.8, carbohydrates: 5.0, fat: 0.5, fiber: 3.0, isVegetable: true },
    "cauliflower": { name: "Cauliflower", protein: 1.9, carbohydrates: 5.0, fat: 0.3, fiber: 2.0, isVegetable: true },
    "brussels sprouts": { name: "Brussels Sprouts", protein: 3.4, carbohydrates: 9.0, fat: 0.3, fiber: 3.8, isVegetable: true },
    "asparagus": { name: "Asparagus", protein: 2.2, carbohydrates: 3.9, fat: 0.1, fiber: 2.1, isVegetable: true },
    "green beans": { name: "Green Beans", protein: 1.8, carbohydrates: 7.0, fat: 0.2, fiber: 2.7, isVegetable: true },
    "french beans": { name: "French Beans", protein: 1.8, carbohydrates: 7.0, fat: 0.2, fiber: 2.7, isVegetable: true },
    "peas": { name: "Peas", protein: 5.4, carbohydrates: 14.5, fat: 0.4, fiber: 5.7, isVegetable: true },
    "green peas": { name: "Green Peas", protein: 5.4, carbohydrates: 14.5, fat: 0.4, fiber: 5.7, isVegetable: true },
    "snap peas": { name: "Snap Peas", protein: 2.8, carbohydrates: 7.5, fat: 0.2, fiber: 2.6, isVegetable: true },
    "snow peas": { name: "Snow Peas", protein: 2.8, carbohydrates: 7.5, fat: 0.2, fiber: 2.6, isVegetable: true },
    "zucchini": { name: "Zucchini", protein: 1.2, carbohydrates: 3.1, fat: 0.3, fiber: 1.0, isVegetable: true },
    "courgette": { name: "Courgette", protein: 1.2, carbohydrates: 3.1, fat: 0.3, fiber: 1.0, isVegetable: true },
    "yellow squash": { name: "Yellow Squash", protein: 1.2, carbohydrates: 3.9, fat: 0.2, fiber: 1.1, isVegetable: true },
    "cucumber": { name: "Cucumber", protein: 0.7, carbohydrates: 3.6, fat: 0.1, fiber: 0.5, isVegetable: true },
    "celery": { name: "Celery", protein: 0.7, carbohydrates: 3.0, fat: 0.2, fiber: 1.6, isVegetable: true },
    "bell pepper": { name: "Bell Pepper", protein: 1.0, carbohydrates: 6.0, fat: 0.3, fiber: 2.1, isVegetable: true },
    "peppers": { name: "Peppers", protein: 1.0, carbohydrates: 6.0, fat: 0.3, fiber: 2.1, isVegetable: true },
    "capsicum": { name: "Capsicum", protein: 1.0, carbohydrates: 6.0, fat: 0.3, fiber: 2.1, isVegetable: true },
    "red pepper": { name: "Red Bell Pepper", protein: 1.0, carbohydrates: 6.0, fat: 0.3, fiber: 2.1, isVegetable: true },
    "green pepper": { name: "Green Bell Pepper", protein: 0.9, carbohydrates: 4.6, fat: 0.2, fiber: 1.7, isVegetable: true },
    "yellow pepper": { name: "Yellow Bell Pepper", protein: 1.0, carbohydrates: 6.3, fat: 0.2, fiber: 1.9, isVegetable: true },
    "chili": { name: "Chili Pepper", protein: 1.9, carbohydrates: 8.8, fat: 0.4, fiber: 1.5, isVegetable: true },
    "jalapeno": { name: "Jalapeno", protein: 0.9, carbohydrates: 6.5, fat: 0.4, fiber: 2.8, isVegetable: true },
    "tomato": { name: "Tomato", protein: 0.9, carbohydrates: 3.9, fat: 0.2, fiber: 1.2, isVegetable: true },
    "tomatoes": { name: "Tomatoes", protein: 0.9, carbohydrates: 3.9, fat: 0.2, fiber: 1.2, isVegetable: true },
    "cherry tomatoes": { name: "Cherry Tomatoes", protein: 0.9, carbohydrates: 3.9, fat: 0.2, fiber: 1.2, isVegetable: true },
    "eggplant": { name: "Eggplant", protein: 1.0, carbohydrates: 6.0, fat: 0.2, fiber: 3.0, isVegetable: true },
    "brinjal": { name: "Brinjal", protein: 1.0, carbohydrates: 6.0, fat: 0.2, fiber: 3.0, isVegetable: true },
    "aubergine": { name: "Aubergine", protein: 1.0, carbohydrates: 6.0, fat: 0.2, fiber: 3.0, isVegetable: true },
    "okra": { name: "Okra", protein: 1.9, carbohydrates: 7.5, fat: 0.2, fiber: 3.2, isVegetable: true },
    "bhindi": { name: "Bhindi", protein: 1.9, carbohydrates: 7.5, fat: 0.2, fiber: 3.2, isVegetable: true },
    "artichoke": { name: "Artichoke", protein: 3.3, carbohydrates: 10.5, fat: 0.2, fiber: 5.4, isVegetable: true },
    "beetroot": { name: "Beetroot", protein: 1.6, carbohydrates: 9.6, fat: 0.2, fiber: 2.8, isVegetable: true },
    "beets": { name: "Beets", protein: 1.6, carbohydrates: 9.6, fat: 0.2, fiber: 2.8, isVegetable: true },
    "radish": { name: "Radish", protein: 0.7, carbohydrates: 3.4, fat: 0.1, fiber: 1.6, isVegetable: true },
    "turnip": { name: "Turnip", protein: 0.9, carbohydrates: 6.4, fat: 0.1, fiber: 1.8, isVegetable: true },
    "carrot": { name: "Carrot", protein: 0.9, carbohydrates: 9.6, fat: 0.2, fiber: 2.8, isVegetable: true },
    "carrots": { name: "Carrots", protein: 0.9, carbohydrates: 9.6, fat: 0.2, fiber: 2.8, isVegetable: true },
    "parsnip": { name: "Parsnip", protein: 1.2, carbohydrates: 18.0, fat: 0.3, fiber: 4.9, isVegetable: true },
    "onion": { name: "Onion", protein: 1.1, carbohydrates: 9.3, fat: 0.1, fiber: 1.7, isVegetable: true },
    "onions": { name: "Onions", protein: 1.1, carbohydrates: 9.3, fat: 0.1, fiber: 1.7, isVegetable: true },
    "red onion": { name: "Red Onion", protein: 1.1, carbohydrates: 9.3, fat: 0.1, fiber: 1.7, isVegetable: true },
    "green onion": { name: "Green Onion", protein: 1.8, carbohydrates: 7.3, fat: 0.2, fiber: 2.6, isVegetable: true },
    "scallion": { name: "Scallion", protein: 1.8, carbohydrates: 7.3, fat: 0.2, fiber: 2.6, isVegetable: true },
    "shallot": { name: "Shallot", protein: 2.5, carbohydrates: 16.8, fat: 0.1, fiber: 3.2, isVegetable: true },
    "leek": { name: "Leek", protein: 1.5, carbohydrates: 14.2, fat: 0.3, fiber: 1.8, isVegetable: true },
    "garlic": { name: "Garlic", protein: 6.4, carbohydrates: 33.1, fat: 0.5, fiber: 2.1, isVegetable: true },
    "ginger": { name: "Ginger", protein: 1.8, carbohydrates: 17.8, fat: 0.8, fiber: 2.0, isVegetable: true },
    "mushrooms": { name: "Mushrooms", protein: 3.1, carbohydrates: 3.3, fat: 0.3, fiber: 1.0, isVegetable: true },
    "mushroom": { name: "Mushroom", protein: 3.1, carbohydrates: 3.3, fat: 0.3, fiber: 1.0, isVegetable: true },
    "shiitake": { name: "Shiitake Mushrooms", protein: 2.2, carbohydrates: 6.8, fat: 0.5, fiber: 2.5, isVegetable: true },
    "portobello": { name: "Portobello Mushrooms", protein: 2.1, carbohydrates: 3.9, fat: 0.4, fiber: 1.3, isVegetable: true },
    "pumpkin": { name: "Pumpkin", protein: 1.0, carbohydrates: 6.5, fat: 0.1, fiber: 0.5, isVegetable: true },
    "butternut squash": { name: "Butternut Squash", protein: 1.0, carbohydrates: 11.7, fat: 0.1, fiber: 2.0, isVegetable: true },

    // Fruits (Fiber & Micronutrients)
    "apple": { name: "Apple", protein: 0.3, carbohydrates: 13.8, fat: 0.2, fiber: 2.4, isVegetable: true },
    "banana": { name: "Banana", protein: 1.1, carbohydrates: 22.8, fat: 0.3, fiber: 2.6, isVegetable: true },
    "orange": { name: "Orange", protein: 0.9, carbohydrates: 11.8, fat: 0.1, fiber: 2.4, isVegetable: true },
    "clementine": { name: "Clementine", protein: 0.9, carbohydrates: 12.0, fat: 0.2, fiber: 1.7, isVegetable: true },
    "lemon": { name: "Lemon", protein: 1.1, carbohydrates: 9.3, fat: 0.3, fiber: 2.8, isVegetable: true },
    "lime": { name: "Lime", protein: 0.7, carbohydrates: 10.5, fat: 0.2, fiber: 2.8, isVegetable: true },
    "strawberry": { name: "Strawberry", protein: 0.7, carbohydrates: 7.7, fat: 0.3, fiber: 2.0, isVegetable: true },
    "strawberries": { name: "Strawberries", protein: 0.7, carbohydrates: 7.7, fat: 0.3, fiber: 2.0, isVegetable: true },
    "blueberry": { name: "Blueberry", protein: 0.7, carbohydrates: 14.5, fat: 0.3, fiber: 2.4, isVegetable: true },
    "blueberries": { name: "Blueberries", protein: 0.7, carbohydrates: 14.5, fat: 0.3, fiber: 2.4, isVegetable: true },
    "raspberry": { name: "Raspberry", protein: 1.2, carbohydrates: 11.9, fat: 0.7, fiber: 6.5, isVegetable: true },
    "raspberries": { name: "Raspberries", protein: 1.2, carbohydrates: 11.9, fat: 0.7, fiber: 6.5, isVegetable: true },
    "blackberry": { name: "Blackberry", protein: 1.4, carbohydrates: 9.6, fat: 0.5, fiber: 5.3, isVegetable: true },
    "blackberries": { name: "Blackberries", protein: 1.4, carbohydrates: 9.6, fat: 0.5, fiber: 5.3, isVegetable: true },
    "cherry": { name: "Cherry", protein: 1.1, carbohydrates: 16.0, fat: 0.2, fiber: 2.1, isVegetable: true },
    "cherries": { name: "Cherries", protein: 1.1, carbohydrates: 16.0, fat: 0.2, fiber: 2.1, isVegetable: true },
    "grapes": { name: "Grapes", protein: 0.7, carbohydrates: 18.1, fat: 0.2, fiber: 0.9, isVegetable: true },
    "watermelon": { name: "Watermelon", protein: 0.6, carbohydrates: 7.6, fat: 0.2, fiber: 0.4, isVegetable: true },
    "melon": { name: "Melon", protein: 0.8, carbohydrates: 8.2, fat: 0.2, fiber: 0.9, isVegetable: true },
    "cantaloupe": { name: "Cantaloupe", protein: 0.8, carbohydrates: 8.2, fat: 0.2, fiber: 0.9, isVegetable: true },
    "mango": { name: "Mango", protein: 0.8, carbohydrates: 15.0, fat: 0.4, fiber: 1.6, isVegetable: true },
    "pineapple": { name: "Pineapple", protein: 0.5, carbohydrates: 13.1, fat: 0.1, fiber: 1.4, isVegetable: true },
    "papaya": { name: "Papaya", protein: 0.5, carbohydrates: 10.8, fat: 0.3, fiber: 1.7, isVegetable: true },
    "peach": { name: "Peach", protein: 0.9, carbohydrates: 9.5, fat: 0.3, fiber: 1.5, isVegetable: true },
    "plum": { name: "Plum", protein: 0.7, carbohydrates: 11.4, fat: 0.3, fiber: 1.4, isVegetable: true },
    "kiwi": { name: "Kiwi", protein: 1.1, carbohydrates: 14.7, fat: 0.5, fiber: 3.0, isVegetable: true },
    "pear": { name: "Pear", protein: 0.4, carbohydrates: 15.2, fat: 0.1, fiber: 3.1, isVegetable: true },
    "fig": { name: "Fig", protein: 0.8, carbohydrates: 19.2, fat: 0.3, fiber: 2.9, isVegetable: true },
    "pomegranate": { name: "Pomegranate", protein: 1.7, carbohydrates: 18.7, fat: 1.2, fiber: 4.0, isVegetable: true },

    // --------------------------------------------------------------------------
    // HEALTHY FATS, OILS, NUTS & SEEDS (High Fat)
    // --------------------------------------------------------------------------
    "avocado": { name: "Avocado", protein: 2.0, carbohydrates: 8.5, fat: 14.7, fiber: 6.7, isVegetable: true },
    "olive oil": { name: "Olive Oil", protein: 0.0, carbohydrates: 0.0, fat: 100.0, fiber: 0.0, isVegetable: false },
    "extra virgin olive oil": { name: "Extra Virgin Olive Oil", protein: 0.0, carbohydrates: 0.0, fat: 100.0, fiber: 0.0, isVegetable: false },
    "oil": { name: "Oil", protein: 0.0, carbohydrates: 0.0, fat: 100.0, fiber: 0.0, isVegetable: false },
    "olives": { name: "Olives", protein: 0.8, carbohydrates: 6.3, fat: 10.7, fiber: 3.2, isVegetable: false },
    "black olives": { name: "Black Olives", protein: 0.8, carbohydrates: 6.3, fat: 10.7, fiber: 3.2, isVegetable: false },
    "green olives": { name: "Green Olives", protein: 1.0, carbohydrates: 3.8, fat: 15.3, fiber: 3.3, isVegetable: false },
    "coconut oil": { name: "Coconut Oil", protein: 0.0, carbohydrates: 0.0, fat: 99.0, fiber: 0.0, isVegetable: false },
    "sesame oil": { name: "Sesame Oil", protein: 0.0, carbohydrates: 0.0, fat: 100.0, fiber: 0.0, isVegetable: false },
    "avocado oil": { name: "Avocado Oil", protein: 0.0, carbohydrates: 0.0, fat: 100.0, fiber: 0.0, isVegetable: false },
    "butter": { name: "Butter", protein: 0.9, carbohydrates: 0.1, fat: 81.0, fiber: 0.0, isVegetable: false },
    "ghee": { name: "Ghee", protein: 0.3, carbohydrates: 0.0, fat: 99.5, fiber: 0.0, isVegetable: false },
    "almonds": { name: "Almonds", protein: 21.2, carbohydrates: 21.6, fat: 49.9, fiber: 12.5, isVegetable: false },
    "almond": { name: "Almond", protein: 21.2, carbohydrates: 21.6, fat: 49.9, fiber: 12.5, isVegetable: false },
    "walnuts": { name: "Walnuts", protein: 15.2, carbohydrates: 13.7, fat: 65.2, fiber: 6.7, isVegetable: false },
    "walnut": { name: "Walnut", protein: 15.2, carbohydrates: 13.7, fat: 65.2, fiber: 6.7, isVegetable: false },
    "cashews": { name: "Cashews", protein: 18.2, carbohydrates: 30.2, fat: 43.8, fiber: 3.3, isVegetable: false },
    "cashew": { name: "Cashew", protein: 18.2, carbohydrates: 30.2, fat: 43.8, fiber: 3.3, isVegetable: false },
    "pecans": { name: "Pecans", protein: 9.2, carbohydrates: 13.9, fat: 72.0, fiber: 9.6, isVegetable: false },
    "pistachios": { name: "Pistachios", protein: 20.2, carbohydrates: 27.2, fat: 45.3, fiber: 10.6, isVegetable: false },
    "hazelnuts": { name: "Hazelnuts", protein: 15.0, carbohydrates: 16.7, fat: 60.8, fiber: 9.7, isVegetable: false },
    "macadamia": { name: "Macadamia Nuts", protein: 7.9, carbohydrates: 13.8, fat: 75.8, fiber: 8.6, isVegetable: false },
    "pine nuts": { name: "Pine Nuts", protein: 13.7, carbohydrates: 13.1, fat: 68.4, fiber: 3.7, isVegetable: false },
    "peanuts": { name: "Peanuts", protein: 25.8, carbohydrates: 16.1, fat: 49.2, fiber: 8.5, isVegetable: false },
    "peanut": { name: "Peanut", protein: 25.8, carbohydrates: 16.1, fat: 49.2, fiber: 8.5, isVegetable: false },
    "peanut butter": { name: "Peanut Butter", protein: 25.0, carbohydrates: 20.0, fat: 50.0, fiber: 6.0, isVegetable: false },
    "almond butter": { name: "Almond Butter", protein: 21.0, carbohydrates: 19.0, fat: 56.0, fiber: 10.0, isVegetable: false },
    "sunflower seeds": { name: "Sunflower Seeds", protein: 20.8, carbohydrates: 20.0, fat: 51.5, fiber: 8.6, isVegetable: false },
    "chia seeds": { name: "Chia Seeds", protein: 16.5, carbohydrates: 42.1, fat: 30.7, fiber: 34.4, isVegetable: false },
    "flaxseed": { name: "Flaxseed", protein: 18.3, carbohydrates: 28.9, fat: 42.2, fiber: 27.3, isVegetable: false },
    "flax seeds": { name: "Flax Seeds", protein: 18.3, carbohydrates: 28.9, fat: 42.2, fiber: 27.3, isVegetable: false },
    "pumpkin seeds": { name: "Pumpkin Seeds", protein: 30.2, carbohydrates: 10.7, fat: 49.1, fiber: 6.0, isVegetable: false },
    "hemp seeds": { name: "Hemp Seeds", protein: 31.6, carbohydrates: 8.7, fat: 48.8, fiber: 4.0, isVegetable: false },
    "sesame seeds": { name: "Sesame Seeds", protein: 17.7, carbohydrates: 23.4, fat: 49.7, fiber: 11.8, isVegetable: false },
    "tahini": { name: "Tahini", protein: 17.0, carbohydrates: 21.0, fat: 54.0, fiber: 9.3, isVegetable: false }
};

window.LOCAL_NUTRITION_DATABASE = LOCAL_NUTRITION_DATABASE;
